-- ============================================================
-- init.sql - Angular Padel Club
-- Version nettoyee pour reset Docker / demo / tests manuels
-- Mot de passe de tous les admins seedes : admin123
-- Hash BCrypt : $2a$10$9WltJ3gI8U9PUKmACR14b.M2ib2YkqlK2jTsUHXGmcQYiwmB7AE7K
-- ============================================================

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET client_min_messages = warning;

-- Nettoyage complet, pratique si le script est rejoue manuellement.
DROP TABLE IF EXISTS public.dette_membre CASCADE;
DROP TABLE IF EXISTS public.paiement CASCADE;
DROP TABLE IF EXISTS public.participation CASCADE;
DROP TABLE IF EXISTS public.match_padel CASCADE;
DROP TABLE IF EXISTS public.reservation CASCADE;
DROP TABLE IF EXISTS public.penalite CASCADE;
DROP TABLE IF EXISTS public.jour_fermeture CASCADE;
DROP TABLE IF EXISTS public.administrateur CASCADE;
DROP TABLE IF EXISTS public.horaire_site CASCADE;
DROP TABLE IF EXISTS public.membre CASCADE;
DROP TABLE IF EXISTS public.terrain CASCADE;
DROP TABLE IF EXISTS public.type_membre CASCADE;
DROP TABLE IF EXISTS public.site CASCADE;

-- ============================================================
-- TABLES DE REFERENCE
-- ============================================================

CREATE TABLE public.site (
                             id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             actif boolean NOT NULL,
                             adresse character varying(255) NOT NULL,
                             code_postal character varying(255) NOT NULL,
                             description character varying(255) NOT NULL,
                             image_url character varying(255) NOT NULL,
                             nom character varying(255) NOT NULL,
                             ville character varying(255) NOT NULL
);

CREATE TABLE public.type_membre (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    code character varying(255) NOT NULL UNIQUE,
                                    delai_reservation_jours integer NOT NULL
);

CREATE TABLE public.terrain (
                                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                site_id integer NOT NULL REFERENCES public.site(id),
                                nom character varying(255) NOT NULL,
                                actif boolean NOT NULL,
                                couvert boolean NOT NULL,
                                maintenance boolean DEFAULT false NOT NULL
);

CREATE TABLE public.horaire_site (
                                     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     site_id integer NOT NULL REFERENCES public.site(id),
                                     annee integer NOT NULL,
                                     heure_debut time(0) without time zone NOT NULL,
                                     heure_fin time(0) without time zone NOT NULL,
                                     duree_match_minutes integer NOT NULL,
                                     pause_minutes integer NOT NULL,
                                     CONSTRAINT uk_horaire_site_annee UNIQUE (site_id, annee)
);

CREATE TABLE public.administrateur (
                                       id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       matricule character varying(10) NOT NULL UNIQUE,
                                       site_id integer REFERENCES public.site(id),
                                       type_admin character varying(20) NOT NULL,
                                       nom character varying(100) NOT NULL,
                                       prenom character varying(100) NOT NULL,
                                       email character varying(150) NOT NULL UNIQUE,
                                       password_hash character varying(255) NOT NULL,
                                       CONSTRAINT administrateur_type_admin_check CHECK (type_admin IN ('GLOBAL', 'SITE')),
                                       CONSTRAINT administrateur_site_coherence_check CHECK (
                                           (type_admin = 'GLOBAL' AND site_id IS NULL)
                                               OR
                                           (type_admin = 'SITE' AND site_id IS NOT NULL)
                                           )
);

CREATE TABLE public.membre (
                               id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               site_id integer REFERENCES public.site(id),
                               type_membre_id integer NOT NULL REFERENCES public.type_membre(id),
                               email character varying(255) NOT NULL UNIQUE,
                               matricule character varying(255) NOT NULL UNIQUE,
                               nom character varying(255) NOT NULL,
                               prenom character varying(255) NOT NULL,
                               actif boolean NOT NULL
);

-- ============================================================
-- TABLES METIER
-- ============================================================

CREATE TABLE public.reservation (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    court_id integer NOT NULL REFERENCES public.terrain(id),
                                    membre_id integer NOT NULL REFERENCES public.membre(id),
                                    date date NOT NULL,
                                    start_time time(0) without time zone NOT NULL,
                                    end_time time(0) without time zone NOT NULL,
                                    statut character varying(50) DEFAULT 'EN_ATTENTE_PAIEMENT' NOT NULL,
                                    CONSTRAINT reservation_statut_check CHECK (statut IN ('EN_ATTENTE_PAIEMENT', 'VALIDEE', 'TERMINEE', 'ANNULEE')),
                                    CONSTRAINT uk_reservation_court_date_start UNIQUE (court_id, date, start_time)
);

CREATE TABLE public.match_padel (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    reservation_id integer NOT NULL REFERENCES public.reservation(id),
                                    terrain_id integer NOT NULL REFERENCES public.terrain(id),
                                    organisateur_id integer NOT NULL REFERENCES public.membre(id),
                                    date_match date NOT NULL,
                                    heure_debut time(0) without time zone NOT NULL,
                                    heure_fin time(0) without time zone NOT NULL,
                                    prix_total integer NOT NULL,
                                    created_at timestamp(6) without time zone,
                                    statut character varying(255) NOT NULL,
                                    type_match character varying(255) NOT NULL,
                                    CONSTRAINT match_padel_statut_check CHECK (statut IN ('PLANIFIE', 'OUVERT', 'COMPLET', 'ANNULE', 'TERMINE')),
                                    CONSTRAINT match_padel_type_match_check CHECK (type_match IN ('PUBLIC', 'PRIVE'))
);

CREATE TABLE public.participation (
                                      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      match_id integer NOT NULL REFERENCES public.match_padel(id),
                                      membre_id integer NOT NULL REFERENCES public.membre(id),
                                      date_inscription timestamp(6) without time zone,
                                      statut character varying(50) DEFAULT 'EN_ATTENTE_PAIEMENT' NOT NULL,
                                      montant_du_centimes integer DEFAULT 1500 NOT NULL,
                                      date_limite_paiement timestamp(6) without time zone,
                                      CONSTRAINT participation_montant_du_centimes_check CHECK (montant_du_centimes >= 0),
                                      CONSTRAINT participation_statut_check CHECK (statut IN ('EN_ATTENTE_PAIEMENT', 'PAYEE', 'LIBEREE', 'ANNULEE')),
                                      CONSTRAINT uk_participation_match_membre UNIQUE (match_id, membre_id)
);

CREATE TABLE public.paiement (
                                 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 reservation_id integer REFERENCES public.reservation(id),
                                 membre_id integer NOT NULL REFERENCES public.membre(id),
                                 participation_match_id integer REFERENCES public.participation(id),
                                 montant_centimes integer NOT NULL,
                                 devise character varying(3) DEFAULT 'EUR'::character varying NOT NULL,
                                 provider character varying(30) DEFAULT 'MOCK'::character varying NOT NULL,
                                 provider_payment_id character varying(255),
                                 client_secret character varying(255),
                                 methode character varying(255) DEFAULT 'CARTE'::character varying NOT NULL,
                                 statut character varying(255) DEFAULT 'EN_ATTENTE'::character varying NOT NULL,
                                 date_creation timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 date_paiement timestamp(6) without time zone,
                                 date_expiration timestamp(6) without time zone,
                                 metadata jsonb,
                                 CONSTRAINT paiement_montant_centimes_check CHECK (montant_centimes > 0),
                                 CONSTRAINT paiement_devise_check CHECK (devise IN ('EUR')),
                                 CONSTRAINT paiement_provider_check CHECK (provider IN ('MOCK', 'STRIPE')),
                                 CONSTRAINT paiement_methode_check CHECK (methode IN ('CARTE', 'CASH', 'VIREMENT')),
                                 CONSTRAINT paiement_statut_check CHECK (statut IN ('EN_ATTENTE', 'VALIDE', 'REFUSE', 'ANNULE', 'REMBOURSE'))
);

CREATE UNIQUE INDEX paiement_provider_payment_id_key
    ON public.paiement (provider_payment_id)
    WHERE provider_payment_id IS NOT NULL;

CREATE TABLE public.dette_membre (
                                     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     membre_id integer NOT NULL REFERENCES public.membre(id),
                                     participation_id integer REFERENCES public.participation(id),
                                     reservation_id integer REFERENCES public.reservation(id),
                                     montant_centimes integer NOT NULL,
                                     statut character varying(50) DEFAULT 'OUVERTE' NOT NULL,
                                     raison character varying(50) DEFAULT 'PARTICIPATION_IMPAYEE' NOT NULL,
                                     date_creation timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     date_resolution timestamp(6) without time zone,
                                     CONSTRAINT dette_membre_montant_centimes_check CHECK (montant_centimes > 0),
                                     CONSTRAINT dette_membre_statut_check CHECK (statut IN ('OUVERTE', 'PAYEE', 'ANNULEE')),
                                     CONSTRAINT dette_membre_raison_check CHECK (raison IN ('PARTICIPATION_IMPAYEE', 'SOLDE_ORGANISATEUR', 'AJUSTEMENT'))
);

CREATE TABLE public.penalite (
                                 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 membre_id integer NOT NULL REFERENCES public.membre(id),
                                 match_id integer REFERENCES public.match_padel(id),
                                 date_debut date NOT NULL,
                                 date_fin date NOT NULL,
                                 raison character varying(255) NOT NULL,
                                 active boolean DEFAULT true NOT NULL
);

CREATE TABLE public.jour_fermeture (
                                       id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       site_id integer REFERENCES public.site(id),
                                       date_fermeture date NOT NULL,
                                       raison character varying(255),
                                       global boolean DEFAULT false NOT NULL
);

CREATE UNIQUE INDEX uk_jour_fermeture_global_date
    ON public.jour_fermeture (date_fermeture)
    WHERE global = true;

CREATE UNIQUE INDEX uk_jour_fermeture_site_date
    ON public.jour_fermeture (site_id, date_fermeture)
    WHERE site_id IS NOT NULL;

-- ============================================================
-- SEED : SITES / TYPES / ADMINS
-- ============================================================

INSERT INTO public.site
(id, actif, adresse, code_postal, description, image_url, nom, ville)
VALUES
    (1, true, 'Avenue de l''Atomium 1', '1020', 'Centre indoor situé au cœur de Bruxelles, idéal pour les parties après le travail et les tournois.', 'images/bruxelles.jpg', 'THE ATOMIUM PADEL CLUB', 'BRUXELLES'),
    (2, true, 'Rue de la Cité 22', '4000', 'Club convivial de la Cité Ardente avec terrains spacieux et club-house animé.', 'images/liege.jpg', 'THE CARRÉ CLUB', 'LIÈGE'),
    (3, true, 'Route du Luxembourg 8', '6700', 'Site calme et verdoyant proche du Luxembourg, parfait pour jouer dans un cadre apaisant.', 'images/arlon.jpg', 'ARLON BLUE PADEL', 'ARLON'),
    (4, true, 'Avenue des Tests 12', '5000', 'Site de test complet avec terrains actifs, en maintenance et inactifs pour les scénarios admin.', 'images/namur.jpg', 'NAMUR TEST PADEL', 'NAMUR');

INSERT INTO public.type_membre
(id, code, delai_reservation_jours)
VALUES
    (1, 'GLOBAL', 21),
    (2, 'SITE', 14),
    (3, 'LIBRE', 5);

INSERT INTO public.administrateur
(id, matricule, site_id, type_admin, nom, prenom, email, password_hash)
VALUES
    (1, 'AG01', NULL, 'GLOBAL', 'Admin', 'Global', 'admin.global@padel.be', '$2y$10$hZ.zLt/Xzc.q1KmeVy6/cuX1k84JMemrya8yY6qVNiImJSCNrmykq'),
    (2, 'AS02', 1, 'SITE', 'Admin', 'Bruxelles', 'admin.bruxelles@padel.be', '$2y$10$hZ.zLt/Xzc.q1KmeVy6/cuX1k84JMemrya8yY6qVNiImJSCNrmykq'),
    (3, 'AS03', 2, 'SITE', 'Admin', 'Liege', 'admin.liege@padel.be', '$2y$10$hZ.zLt/Xzc.q1KmeVy6/cuX1k84JMemrya8yY6qVNiImJSCNrmykq'),
    (4, 'AS04', 3, 'SITE', 'Admin', 'Arlon', 'admin.arlon@padel.be', '$2y$10$hZ.zLt/Xzc.q1KmeVy6/cuX1k84JMemrya8yY6qVNiImJSCNrmykq'),
    (5, 'AS05', 4, 'SITE', 'Admin', 'Namur', 'admin.namur@padel.be', '$2y$10$hZ.zLt/Xzc.q1KmeVy6/cuX1k84JMemrya8yY6qVNiImJSCNrmykq');
INSERT INTO public.horaire_site
(id, site_id, annee, heure_debut, heure_fin, duree_match_minutes, pause_minutes)
VALUES
    (1, 1, 2026, '08:00:00', '22:00:00', 90, 15),
    (2, 2, 2026, '09:00:00', '21:00:00', 90, 15),
    (3, 3, 2026, '08:30:00', '21:30:00', 90, 15),
    (4, 4, 2026, '07:30:00', '22:30:00', 90, 15),
    (5, 1, 2027, '08:00:00', '22:00:00', 90, 15);

INSERT INTO public.terrain
(id, site_id, nom, actif, couvert, maintenance)
VALUES
    (1, 1, 'B1', true, true, false),
    (2, 1, 'B2-MAINTENANCE', true, false, true),
    (10, 1, 'B3', true, true, false),
    (3, 2, 'L1', true, true, false),
    (4, 2, 'L2', true, false, false),
    (5, 3, 'A1', true, true, false),
    (6, 3, 'A2', true, false, false),
    (7, 4, 'N1', true, true, false),
    (8, 4, 'N2-MAINTENANCE', true, false, true),
    (9, 4, 'N3-INACTIF', false, true, false);

INSERT INTO public.jour_fermeture
(id, site_id, date_fermeture, raison, global)
VALUES
    (1, NULL, '2026-01-01', 'Nouvel an', true),
    (2, NULL, '2026-12-25', 'Noël', true),
    (3, 1, '2026-07-21', 'Fermeture exceptionnelle Bruxelles', false),
    (4, 2, '2026-08-15', 'Fermeture exceptionnelle Liège', false),
    (5, 3, '2026-11-11', 'Fermeture exceptionnelle Arlon', false),
    (6, 4, '2026-09-27', 'Fermeture exceptionnelle Namur', false),
    (7, NULL, '2027-01-01', 'Nouvel an', true);

-- ============================================================
-- SEED : MEMBRES
-- ============================================================

INSERT INTO public.membre
(id, site_id, type_membre_id, email, matricule, nom, prenom, actif)
VALUES
    (1, NULL, 1, 'jean.dupont@mail.com', 'G0001', 'Dupont', 'Jean', true),
    (2, NULL, 1, 'sophie.lambert@mail.com', 'G0002', 'Lambert', 'Sophie', true),
    (18, NULL, 1, 'global.test@mail.com', 'G0004', 'Global', 'Test', true),
    (10, NULL, 1, 'arthur.pendragon@mail.com', 'G0003', 'Pendragon', 'Arthur', false),

    (3, 1, 2, 'claire.martin@mail.com', 'S0001', 'Martin', 'Claire', true),
    (4, 1, 2, 'lucas.bernard@mail.com', 'S0002', 'Bernard', 'Lucas', true),
    (15, 1, 2, 'mila.dubois@mail.com', 'S0007', 'Dubois', 'Mila', true),

    (5, 2, 2, 'emma.moreau@mail.com', 'S0003', 'Moreau', 'Emma', true),
    (16, 2, 2, 'adam.rossi@mail.com', 'S0008', 'Rossi', 'Adam', true),

    (6, 3, 2, 'noah.lefevre@mail.com', 'S0004', 'Lefevre', 'Noah', true),

    (11, 4, 2, 'lea.fontaine@mail.com', 'S0005', 'Fontaine', 'Lea', true),
    (12, 4, 2, 'tom.vermeulen@mail.com', 'S0006', 'Vermeulen', 'Tom', true),
    (17, 4, 2, 'inactive.test@mail.com', 'S0099', 'Inactive', 'Test', false),

    (7, NULL, 3, 'hugo.petit@mail.com', 'L0001', 'Petit', 'Hugo', true),
    (8, NULL, 3, 'alice.durand@mail.com', 'L0002', 'Durand', 'Alice', true),
    (9, NULL, 3, 'nathan.simon@mail.com', 'L0003', 'Simon', 'Nathan', true),
    (13, NULL, 3, 'ines.laurent@mail.com', 'L0004', 'Laurent', 'Ines', true),
    (14, NULL, 3, 'yanis.michel@mail.com', 'L0005', 'Michel', 'Yanis', true);

-- ============================================================
-- SEED : RESERVATIONS / MATCHES ACTUELS
-- Dates cohérentes avec une remise au 31/05/2026.
-- Les matches passés sont TERMINE/TERMINEE.
-- Les matches futurs restent OUVERT/COMPLET/ANNULE.
-- ============================================================

INSERT INTO public.reservation
(id, court_id, membre_id, date, start_time, end_time, statut)
VALUES
    (10, 1, 1, '2026-05-30', '12:30:00', '14:00:00', 'TERMINEE'),
    (11, 1, 1, '2026-05-30', '15:00:00', '16:30:00', 'TERMINEE'),
    (12, 4, 1, '2026-05-26', '14:00:00', '15:30:00', 'TERMINEE'),

    (45, 3, 2, '2026-06-08', '11:00:00', '12:30:00', 'VALIDEE'),
    (46, 4, 1, '2026-06-02', '12:30:00', '14:00:00', 'VALIDEE'),
    (47, 6, 1, '2026-06-15', '10:00:00', '11:30:00', 'VALIDEE'),
    (48, 7, 11, '2026-06-20', '09:00:00', '10:30:00', 'EN_ATTENTE_PAIEMENT'),
    (49, 7, 11, '2026-06-20', '11:00:00', '12:30:00', 'VALIDEE'),
    (50, 8, 12, '2026-06-20', '14:00:00', '15:30:00', 'ANNULEE'),
    (51, 10, 3, '2026-06-21', '10:00:00', '11:30:00', 'VALIDEE'),
    (52, 2, 4, '2026-05-20', '18:00:00', '19:30:00', 'TERMINEE'),
    (53, 5, 13, '2026-06-22', '18:00:00', '19:30:00', 'EN_ATTENTE_PAIEMENT'),
    (54, 8, 12, '2026-06-23', '07:30:00', '09:00:00', 'ANNULEE'),
    (55, 10, 14, '2026-06-23', '16:00:00', '17:30:00', 'ANNULEE'),
    (56, 1, 15, '2026-06-24', '19:00:00', '20:30:00', 'ANNULEE'),
    (57, 3, 16, '2026-06-25', '09:30:00', '11:00:00', 'VALIDEE'),
    (58, 6, 18, '2026-06-26', '12:00:00', '13:30:00', 'VALIDEE');

INSERT INTO public.match_padel
(id, reservation_id, terrain_id, organisateur_id, date_match, heure_debut, heure_fin, prix_total, created_at, statut, type_match)
VALUES
    (6, 10, 1, 1, '2026-05-30', '12:30:00', '14:00:00', 60, '2026-05-24 12:00:00', 'TERMINE', 'PRIVE'),
    (7, 11, 1, 1, '2026-05-30', '15:00:00', '16:30:00', 60, '2026-05-24 17:05:50', 'TERMINE', 'PUBLIC'),
    (8, 12, 4, 1, '2026-05-26', '14:00:00', '15:30:00', 60, '2026-05-24 17:41:39', 'TERMINE', 'PUBLIC'),

    (41, 45, 3, 2, '2026-06-08', '11:00:00', '12:30:00', 60, '2026-05-25 10:56:53', 'OUVERT', 'PUBLIC'),
    (42, 46, 4, 1, '2026-06-02', '12:30:00', '14:00:00', 60, '2026-05-25 11:11:21', 'OUVERT', 'PUBLIC'),
    (43, 47, 6, 1, '2026-06-15', '10:00:00', '11:30:00', 60, '2026-05-25 11:22:37', 'OUVERT', 'PUBLIC'),
    (44, 48, 7, 11, '2026-06-20', '09:00:00', '10:30:00', 60, '2026-05-26 09:00:00', 'OUVERT', 'PUBLIC'),
    (45, 49, 7, 11, '2026-06-20', '11:00:00', '12:30:00', 60, '2026-05-26 09:10:00', 'OUVERT', 'PUBLIC'),
    (46, 50, 8, 12, '2026-06-20', '14:00:00', '15:30:00', 60, '2026-05-26 09:20:00', 'ANNULE', 'PUBLIC'),
    (47, 51, 10, 3, '2026-06-21', '10:00:00', '11:30:00', 60, '2026-05-26 09:30:00', 'COMPLET', 'PRIVE'),
    (48, 52, 2, 4, '2026-05-20', '18:00:00', '19:30:00', 60, '2026-05-19 09:30:00', 'TERMINE', 'PUBLIC'),
    (49, 53, 5, 13, '2026-06-22', '18:00:00', '19:30:00', 60, '2026-05-26 10:00:00', 'OUVERT', 'PUBLIC'),
    (50, 55, 10, 14, '2026-06-23', '16:00:00', '17:30:00', 60, '2026-05-26 10:30:00', 'ANNULE', 'PUBLIC'),
    (51, 56, 1, 15, '2026-06-24', '19:00:00', '20:30:00', 60, '2026-05-26 11:00:00', 'ANNULE', 'PUBLIC'),
    (52, 57, 3, 16, '2026-06-25', '09:30:00', '11:00:00', 60, '2026-05-26 11:30:00', 'OUVERT', 'PUBLIC');

INSERT INTO public.participation
(id, match_id, membre_id, date_inscription, statut, montant_du_centimes, date_limite_paiement)
VALUES
    (11, 6, 1, '2026-05-24 12:01:00', 'PAYEE', 1500, '2026-05-29 12:30:00'),
    (12, 6, 8, '2026-05-24 12:02:00', 'PAYEE', 1500, '2026-05-29 12:30:00'),
    (13, 6, 2, '2026-05-24 12:03:00', 'PAYEE', 1500, '2026-05-29 12:30:00'),
    (14, 6, 7, '2026-05-24 12:04:00', 'PAYEE', 1500, '2026-05-29 12:30:00'),

    (15, 7, 1, '2026-05-24 17:06:00', 'PAYEE', 1500, '2026-05-29 15:00:00'),
    (16, 8, 1, '2026-05-24 17:41:39', 'PAYEE', 1500, '2026-05-25 14:00:00'),

    (49, 41, 2, '2026-05-25 10:56:53', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-07 11:00:00'),
    (50, 42, 1, '2026-05-25 11:11:21', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-01 12:30:00'),
    (51, 43, 1, '2026-05-25 11:22:37', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-14 10:00:00'),

    (52, 44, 11, '2026-05-26 09:00:02', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-19 09:00:00'),
    (53, 45, 11, '2026-05-26 09:10:02', 'PAYEE', 1500, '2026-06-19 11:00:00'),
    (54, 45, 12, '2026-05-26 09:12:00', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-19 11:00:00'),
    (55, 45, 13, '2026-05-26 09:13:00', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-19 11:00:00'),

    (56, 46, 12, '2026-05-26 09:20:02', 'ANNULEE', 1500, '2026-06-19 14:00:00'),

    (57, 47, 3, '2026-05-26 09:30:02', 'PAYEE', 1500, '2026-06-20 10:00:00'),
    (58, 47, 4, '2026-05-26 09:31:02', 'PAYEE', 1500, '2026-06-20 10:00:00'),
    (59, 47, 15, '2026-05-26 09:32:02', 'PAYEE', 1500, '2026-06-20 10:00:00'),
    (60, 47, 18, '2026-05-26 09:33:02', 'PAYEE', 1500, '2026-06-20 10:00:00'),

    (61, 49, 13, '2026-05-26 10:00:02', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-21 18:00:00'),
    (62, 50, 14, '2026-05-26 10:30:02', 'ANNULEE', 1500, '2026-06-22 16:00:00'),
    (63, 51, 15, '2026-05-26 11:00:02', 'ANNULEE', 1500, '2026-06-23 19:00:00'),
    (64, 52, 16, '2026-05-26 11:30:02', 'PAYEE', 1500, '2026-06-24 09:30:00'),
    (65, 52, 5, '2026-05-26 11:35:02', 'EN_ATTENTE_PAIEMENT', 1500, '2026-06-24 09:30:00');

-- ============================================================
-- SEED : PAIEMENTS ET DETTES ACTUELS
-- ============================================================

INSERT INTO public.paiement
(id, reservation_id, membre_id, participation_match_id, montant_centimes, devise, provider, provider_payment_id, client_secret, methode, statut, date_creation, date_paiement, date_expiration, metadata)
VALUES
    (7, 10, 1, 11, 1500, 'EUR', 'MOCK', 'mock_pi_seed_10_1', NULL, 'CARTE', 'VALIDE', '2026-05-24 12:00:00', '2026-05-24 12:01:00', NULL, '{"scenario": "match prive complet"}'),
    (9, 10, 8, 12, 1500, 'EUR', 'MOCK', 'mock_pi_seed_10_2', NULL, 'CARTE', 'VALIDE', '2026-05-24 12:02:00', '2026-05-24 12:03:00', NULL, '{"scenario": "match prive complet"}'),
    (10, 10, 2, 13, 1500, 'EUR', 'MOCK', 'mock_pi_seed_10_3', NULL, 'CARTE', 'VALIDE', '2026-05-24 12:04:00', '2026-05-24 12:05:00', NULL, '{"scenario": "match prive complet"}'),
    (11, 10, 7, 14, 1500, 'EUR', 'MOCK', 'mock_pi_seed_10_4', NULL, 'CARTE', 'VALIDE', '2026-05-24 12:06:00', '2026-05-24 12:07:00', NULL, '{"scenario": "match prive complet"}'),

    (8, 11, 1, 15, 1500, 'EUR', 'MOCK', 'mock_pi_seed_11', NULL, 'CARTE', 'VALIDE', '2026-05-24 17:05:50', '2026-05-24 17:06:30', NULL, '{"scenario": "match public termine incomplet"}'),
    (12, 12, 1, 16, 1500, 'EUR', 'MOCK', 'mock_pi_seed_12', NULL, 'CARTE', 'VALIDE', '2026-05-24 17:42:00', '2026-05-24 17:43:00', NULL, '{"scenario": "match public termine"}'),

    (1, 48, 11, 52, 1500, 'EUR', 'MOCK', 'mock_pi_pending_48', 'mock_secret_pending_48', 'CARTE', 'EN_ATTENTE', '2026-05-26 09:00:05', NULL, '2026-05-26 09:15:05', '{"scenario": "participation publique en attente"}'),
    (2, 49, 11, 53, 1500, 'EUR', 'MOCK', 'mock_pi_paid_49', 'mock_secret_paid_49', 'CARTE', 'VALIDE', '2026-05-26 09:10:05', '2026-05-26 09:11:10', NULL, '{"scenario": "participation publique payee"}'),
    (3, 53, 13, 61, 1500, 'EUR', 'MOCK', 'mock_pi_refused_53', 'mock_secret_refused_53', 'CARTE', 'REFUSE', '2026-05-26 10:00:05', NULL, NULL, '{"scenario": "paiement refuse"}'),
    (4, 55, 14, 62, 1500, 'EUR', 'MOCK', 'mock_pi_cancelled_55', 'mock_secret_cancelled_55', 'CARTE', 'ANNULE', '2026-05-26 10:30:05', NULL, '2026-05-26 10:45:05', '{"scenario": "paiement annule"}'),
    (5, 56, 15, 63, 1500, 'EUR', 'MOCK', 'mock_pi_refunded_56', 'mock_secret_refunded_56', 'CARTE', 'REMBOURSE', '2026-05-26 11:00:05', '2026-05-26 11:01:10', NULL, '{"scenario": "paiement rembourse"}'),
    (6, 57, 16, 64, 1500, 'EUR', 'MOCK', 'mock_pi_cash_57', NULL, 'CASH', 'VALIDE', '2026-05-26 11:30:05', '2026-05-26 11:32:00', NULL, '{"scenario": "paiement cash valide"}');

INSERT INTO public.dette_membre
(id, membre_id, participation_id, reservation_id, montant_centimes, statut, raison, date_creation, date_resolution)
VALUES
    (1, 13, 61, 53, 1500, 'OUVERTE', 'PARTICIPATION_IMPAYEE', '2026-05-27 10:00:00', NULL),
    (2, 18, NULL, 58, 3000, 'OUVERTE', 'SOLDE_ORGANISATEUR', '2026-05-27 11:00:00', NULL),
    (3, 15, 63, 56, 1500, 'PAYEE', 'AJUSTEMENT', '2026-05-26 11:10:00', '2026-05-26 12:00:00'),
    (4, 1, NULL, 11, 4500, 'OUVERTE', 'SOLDE_ORGANISATEUR', '2026-05-30 17:00:00', NULL);

INSERT INTO public.penalite
(id, membre_id, match_id, date_debut, date_fin, raison, active)
VALUES
    (1, 14, 50, '2026-06-23', '2026-06-30', 'Annulation tardive / place libérée', true),
    (2, 10, NULL, '2026-05-01', '2026-05-08', 'Pénalité historique expirée', false);

-- ============================================================
-- SEED : HISTORIQUE POUR ADMIN / STATISTIQUES
-- ============================================================

INSERT INTO public.reservation
(id, court_id, membre_id, date, start_time, end_time, statut)
VALUES
    (70, 1, 1, '2026-01-12', '18:00:00', '19:30:00', 'TERMINEE'),
    (71, 3, 5, '2026-01-15', '19:00:00', '20:30:00', 'TERMINEE'),
    (72, 7, 11, '2026-02-02', '09:30:00', '11:00:00', 'TERMINEE'),
    (73, 10, 3, '2026-02-14', '11:00:00', '12:30:00', 'TERMINEE'),
    (74, 5, 13, '2026-03-03', '17:00:00', '18:30:00', 'TERMINEE'),
    (75, 6, 18, '2026-03-10', '18:00:00', '19:30:00', 'ANNULEE'),
    (76, 4, 1, '2026-04-05', '15:00:00', '16:30:00', 'TERMINEE'),
    (77, 2, 4, '2026-04-12', '16:00:00', '17:30:00', 'ANNULEE'),
    (78, 8, 12, '2026-04-20', '09:00:00', '10:30:00', 'ANNULEE'),
    (79, 1, 2, '2026-05-05', '19:00:00', '20:30:00', 'TERMINEE'),
    (80, 3, 16, '2026-05-18', '10:00:00', '11:30:00', 'TERMINEE');

INSERT INTO public.match_padel
(id, reservation_id, terrain_id, organisateur_id, date_match, heure_debut, heure_fin, prix_total, created_at, statut, type_match)
VALUES
    (60, 70, 1, 1, '2026-01-12', '18:00:00', '19:30:00', 60, '2026-01-05 09:00:00', 'TERMINE', 'PUBLIC'),
    (61, 71, 3, 5, '2026-01-15', '19:00:00', '20:30:00', 60, '2026-01-07 10:00:00', 'TERMINE', 'PUBLIC'),
    (62, 72, 7, 11, '2026-02-02', '09:30:00', '11:00:00', 60, '2026-01-25 11:00:00', 'TERMINE', 'PUBLIC'),
    (63, 73, 10, 3, '2026-02-14', '11:00:00', '12:30:00', 60, '2026-02-01 12:00:00', 'TERMINE', 'PRIVE'),
    (64, 74, 5, 13, '2026-03-03', '17:00:00', '18:30:00', 60, '2026-02-20 13:00:00', 'TERMINE', 'PUBLIC'),
    (65, 75, 6, 18, '2026-03-10', '18:00:00', '19:30:00', 60, '2026-02-25 14:00:00', 'ANNULE', 'PUBLIC'),
    (66, 76, 4, 1, '2026-04-05', '15:00:00', '16:30:00', 60, '2026-03-20 10:30:00', 'TERMINE', 'PUBLIC'),
    (67, 77, 2, 4, '2026-04-12', '16:00:00', '17:30:00', 60, '2026-04-01 08:30:00', 'ANNULE', 'PUBLIC'),
    (68, 78, 8, 12, '2026-04-20', '09:00:00', '10:30:00', 60, '2026-04-04 09:30:00', 'ANNULE', 'PUBLIC'),
    (69, 79, 1, 2, '2026-05-05', '19:00:00', '20:30:00', 60, '2026-04-18 12:00:00', 'TERMINE', 'PUBLIC'),
    (70, 80, 3, 16, '2026-05-18', '10:00:00', '11:30:00', 60, '2026-05-02 15:00:00', 'TERMINE', 'PUBLIC');

INSERT INTO public.participation
(id, match_id, membre_id, date_inscription, statut, montant_du_centimes, date_limite_paiement)
VALUES
    (80, 60, 1, '2026-01-05 09:01:00', 'PAYEE', 1500, '2026-01-11 18:00:00'),
    (81, 61, 5, '2026-01-07 10:01:00', 'PAYEE', 1500, '2026-01-14 19:00:00'),
    (82, 62, 11, '2026-01-25 11:01:00', 'PAYEE', 1500, '2026-02-01 09:30:00'),
    (83, 63, 3, '2026-02-01 12:01:00', 'PAYEE', 1500, '2026-02-13 11:00:00'),
    (84, 63, 4, '2026-02-01 12:02:00', 'PAYEE', 1500, '2026-02-13 11:00:00'),
    (85, 63, 15, '2026-02-01 12:03:00', 'PAYEE', 1500, '2026-02-13 11:00:00'),
    (86, 63, 18, '2026-02-01 12:04:00', 'PAYEE', 1500, '2026-02-13 11:00:00'),
    (87, 64, 13, '2026-02-20 13:01:00', 'PAYEE', 1500, '2026-03-02 17:00:00'),
    (88, 65, 18, '2026-02-25 14:01:00', 'ANNULEE', 1500, '2026-03-09 18:00:00'),
    (89, 66, 1, '2026-03-20 10:31:00', 'PAYEE', 1500, '2026-04-04 15:00:00'),
    (90, 67, 4, '2026-04-01 08:31:00', 'ANNULEE', 1500, '2026-04-11 16:00:00'),
    (91, 68, 12, '2026-04-04 09:31:00', 'ANNULEE', 1500, '2026-04-19 09:00:00'),
    (92, 69, 2, '2026-04-18 12:01:00', 'PAYEE', 1500, '2026-05-04 19:00:00'),
    (93, 70, 16, '2026-05-02 15:01:00', 'PAYEE', 1500, '2026-05-17 10:00:00');

INSERT INTO public.paiement
(id, reservation_id, membre_id, participation_match_id, montant_centimes, devise, provider, provider_payment_id, client_secret, methode, statut, date_creation, date_paiement, date_expiration, metadata)
VALUES
    (20, 70, 1, 80, 1500, 'EUR', 'MOCK', 'mock_hist_jan_70', NULL, 'CARTE', 'VALIDE', '2026-01-05 09:02:00', '2026-01-05 09:03:00', NULL, '{"scenario": "historique janvier Bruxelles"}'),
    (21, 71, 5, 81, 1500, 'EUR', 'MOCK', 'mock_hist_jan_71', NULL, 'CARTE', 'VALIDE', '2026-01-07 10:02:00', '2026-01-07 10:03:00', NULL, '{"scenario": "historique janvier Liège"}'),
    (22, 72, 11, 82, 1500, 'EUR', 'MOCK', 'mock_hist_feb_72', NULL, 'CARTE', 'VALIDE', '2026-01-25 11:02:00', '2026-01-25 11:03:00', NULL, '{"scenario": "historique février Namur"}'),
    (23, 73, 3, 83, 1500, 'EUR', 'MOCK', 'mock_hist_feb_73_1', NULL, 'CARTE', 'VALIDE', '2026-02-01 12:05:00', '2026-02-01 12:06:00', NULL, '{"scenario": "match privé historique"}'),
    (24, 73, 4, 84, 1500, 'EUR', 'MOCK', 'mock_hist_feb_73_2', NULL, 'CARTE', 'VALIDE', '2026-02-01 12:07:00', '2026-02-01 12:08:00', NULL, '{"scenario": "match privé historique"}'),
    (25, 73, 15, 85, 1500, 'EUR', 'MOCK', 'mock_hist_feb_73_3', NULL, 'CARTE', 'VALIDE', '2026-02-01 12:09:00', '2026-02-01 12:10:00', NULL, '{"scenario": "match privé historique"}'),
    (26, 73, 18, 86, 1500, 'EUR', 'MOCK', 'mock_hist_feb_73_4', NULL, 'CARTE', 'VALIDE', '2026-02-01 12:11:00', '2026-02-01 12:12:00', NULL, '{"scenario": "match privé historique"}'),
    (27, 74, 13, 87, 1500, 'EUR', 'MOCK', 'mock_hist_mar_74', NULL, 'CARTE', 'VALIDE', '2026-02-20 13:02:00', '2026-02-20 13:03:00', NULL, '{"scenario": "historique mars Arlon"}'),
    (28, 75, 18, 88, 1500, 'EUR', 'MOCK', 'mock_hist_refund_75', NULL, 'CARTE', 'REMBOURSE', '2026-02-25 14:02:00', '2026-02-25 14:03:00', NULL, '{"scenario": "remboursement fermeture historique"}'),
    (29, 76, 1, 89, 1500, 'EUR', 'MOCK', 'mock_hist_apr_76', NULL, 'CASH', 'VALIDE', '2026-03-20 10:32:00', '2026-03-20 10:33:00', NULL, '{"scenario": "historique avril Liège"}'),
    (30, 77, 4, 90, 1500, 'EUR', 'MOCK', 'mock_hist_refund_77', NULL, 'CARTE', 'REMBOURSE', '2026-04-01 08:32:00', '2026-04-01 08:33:00', NULL, '{"scenario": "remboursement maintenance B2"}'),
    (31, 79, 2, 92, 1500, 'EUR', 'MOCK', 'mock_hist_may_79', NULL, 'CARTE', 'VALIDE', '2026-04-18 12:02:00', '2026-04-18 12:03:00', NULL, '{"scenario": "historique mai Bruxelles"}'),
    (32, 80, 16, 93, 1500, 'EUR', 'MOCK', 'mock_hist_may_80', NULL, 'VIREMENT', 'VALIDE', '2026-05-02 15:02:00', '2026-05-02 15:03:00', NULL, '{"scenario": "historique mai Liège"}');

-- ============================================================
-- ALIGNEMENT DES SEQUENCES
-- ============================================================

SELECT setval(pg_get_serial_sequence('public.administrateur', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.administrateur), true);
SELECT setval(pg_get_serial_sequence('public.dette_membre', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.dette_membre), true);
SELECT setval(pg_get_serial_sequence('public.horaire_site', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.horaire_site), true);
SELECT setval(pg_get_serial_sequence('public.jour_fermeture', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.jour_fermeture), true);
SELECT setval(pg_get_serial_sequence('public.match_padel', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.match_padel), true);
SELECT setval(pg_get_serial_sequence('public.membre', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.membre), true);
SELECT setval(pg_get_serial_sequence('public.paiement', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.paiement), true);
SELECT setval(pg_get_serial_sequence('public.participation', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.participation), true);
SELECT setval(pg_get_serial_sequence('public.penalite', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.penalite), true);
SELECT setval(pg_get_serial_sequence('public.reservation', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.reservation), true);
SELECT setval(pg_get_serial_sequence('public.site', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.site), true);
SELECT setval(pg_get_serial_sequence('public.terrain', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.terrain), true);
SELECT setval(pg_get_serial_sequence('public.type_membre', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.type_membre), true);
