--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 17.0

-- Started on 2026-05-25 11:30:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
--SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: padel_app
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO padel_app;

--
-- TOC entry 3548 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: padel_app
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24762)
-- Name: administrateur; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.administrateur (
                                       id integer NOT NULL,
                                       matricule character varying(10) NOT NULL,
                                       site_id integer,
                                       type_admin character varying(20) NOT NULL,
                                       nom character varying(100) NOT NULL,
                                       prenom character varying(100) NOT NULL,
                                       email character varying(150) NOT NULL
);


ALTER TABLE public.administrateur OWNER TO padel_app;

--
-- TOC entry 219 (class 1259 OID 24761)
-- Name: administrateur_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.administrateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administrateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24770)
-- Name: horaire_site; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.horaire_site (
                                     annee integer NOT NULL,
                                     duree_match_minutes integer NOT NULL,
                                     heure_debut time(0) without time zone NOT NULL,
                                     heure_fin time(0) without time zone NOT NULL,
                                     id integer NOT NULL,
                                     pause_minutes integer NOT NULL,
                                     site_id integer NOT NULL
);


ALTER TABLE public.horaire_site OWNER TO padel_app;

--
-- TOC entry 221 (class 1259 OID 24769)
-- Name: horaire_site_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.horaire_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horaire_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16396)
-- Name: jour_fermeture; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.jour_fermeture (
                                       id integer NOT NULL,
                                       site_id integer,
                                       date_fermeture date NOT NULL,
                                       raison character varying(255),
                                       global boolean DEFAULT false NOT NULL
);


ALTER TABLE public.jour_fermeture OWNER TO padel_app;

--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: jour_fermeture_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

CREATE SEQUENCE public.jour_fermeture_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jour_fermeture_id_seq OWNER TO padel_app;

--
-- TOC entry 3550 (class 0 OID 0)
-- Dependencies: 216
-- Name: jour_fermeture_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: padel_app
--

ALTER SEQUENCE public.jour_fermeture_id_seq OWNED BY public.jour_fermeture.id;


--
-- TOC entry 224 (class 1259 OID 24776)
-- Name: match_padel; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.match_padel (
                                    date_match date NOT NULL,
                                    heure_debut time(0) without time zone NOT NULL,
                                    heure_fin time(0) without time zone NOT NULL,
                                    id integer NOT NULL,
                                    organisateur_id integer NOT NULL,
                                    prix_total integer NOT NULL,
                                    terrain_id integer NOT NULL,
                                    reservation_id integer NOT NULL,
                                    created_at timestamp(6) without time zone,
                                    statut character varying(255) NOT NULL,
                                    type_match character varying(255) NOT NULL,

                                    CONSTRAINT match_padel_statut_check CHECK (
                                        statut IN ('PLANIFIE', 'OUVERT', 'COMPLET', 'ANNULE', 'TERMINE')
                                        ),

                                    CONSTRAINT match_padel_type_match_check CHECK (
                                        type_match IN ('PUBLIC', 'PRIVE')
                                        )
);


ALTER TABLE public.match_padel OWNER TO padel_app;

--
-- TOC entry 223 (class 1259 OID 24775)
-- Name: match_padel_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.match_padel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.match_padel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24786)
-- Name: membre; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.membre (
                               actif boolean NOT NULL,
                               id integer NOT NULL,
                               site_id integer,
                               type_membre_id integer NOT NULL,
                               email character varying(255) NOT NULL,
                               matricule character varying(255) NOT NULL,
                               nom character varying(255) NOT NULL,
                               prenom character varying(255) NOT NULL
);


ALTER TABLE public.membre OWNER TO padel_app;

--
-- TOC entry 225 (class 1259 OID 24785)
-- Name: membre_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.membre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 24796)
-- Name: paiement; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.paiement (
                                 id integer NOT NULL,
                                 montant double precision NOT NULL,
                                 participation_match_id integer NOT NULL,
                                 date_paiement timestamp(6) without time zone NOT NULL,
                                 methode character varying(255) NOT NULL,
                                 statut character varying(255) NOT NULL,
                                 CONSTRAINT paiement_methode_check CHECK (((methode)::text = ANY ((ARRAY['CARTE'::character varying, 'CASH'::character varying, 'VIREMENT'::character varying])::text[]))),
    CONSTRAINT paiement_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'VALIDE'::character varying, 'REFUSE'::character varying])::text[])))
);


ALTER TABLE public.paiement OWNER TO padel_app;

--
-- TOC entry 227 (class 1259 OID 24795)
-- Name: paiement_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.paiement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paiement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24806)
-- Name: participation; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.participation (
                                      id integer NOT NULL,
                                      match_id integer NOT NULL,
                                      membre_id integer NOT NULL,
                                      paiement_id integer,
                                      date_inscription timestamp(6) without time zone
);


ALTER TABLE public.participation OWNER TO padel_app;

--
-- TOC entry 229 (class 1259 OID 24805)
-- Name: participation_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.participation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16426)
-- Name: penalite; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.penalite (
                                 id integer NOT NULL,
                                 membre_id integer NOT NULL,
                                 match_id integer,
                                 date_debut date NOT NULL,
                                 date_fin date NOT NULL,
                                 raison character varying(255) NOT NULL,
                                 active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.penalite OWNER TO padel_app;

--
-- TOC entry 218 (class 1259 OID 16430)
-- Name: penalite_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

CREATE SEQUENCE public.penalite_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.penalite_id_seq OWNER TO padel_app;

--
-- TOC entry 3551 (class 0 OID 0)
-- Dependencies: 218
-- Name: penalite_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: padel_app
--

ALTER SEQUENCE public.penalite_id_seq OWNED BY public.penalite.id;


--
-- TOC entry 232 (class 1259 OID 24814)
-- Name: reservation; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.reservation (
                                    court_id integer NOT NULL,
                                    date date NOT NULL,
                                    end_time time(0) without time zone NOT NULL,
                                    id integer NOT NULL,
                                    membre_id integer NOT NULL,
                                    start_time time(0) without time zone NOT NULL,
                                    statut character varying(50) NOT NULL DEFAULT 'VALIDEE'
);


ALTER TABLE public.reservation OWNER TO padel_app;

--
-- TOC entry 231 (class 1259 OID 24813)
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 24820)
-- Name: site; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.site (
                             actif boolean NOT NULL,
                             id integer NOT NULL,
                             adresse character varying(255) NOT NULL,
                             code_postal character varying(255) NOT NULL,
                             description character varying(255) NOT NULL,
                             image_url character varying(255) NOT NULL,
                             nom character varying(255) NOT NULL,
                             ville character varying(255) NOT NULL
);


ALTER TABLE public.site OWNER TO padel_app;

--
-- TOC entry 233 (class 1259 OID 24819)
-- Name: site_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 24828)
-- Name: terrain; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.terrain (
                                actif boolean NOT NULL,
                                couvert boolean NOT NULL,
                                id integer NOT NULL,
                                site_id integer NOT NULL,
                                nom character varying(255) NOT NULL
);


ALTER TABLE public.terrain OWNER TO padel_app;

--
-- TOC entry 235 (class 1259 OID 24827)
-- Name: terrain_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.terrain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terrain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 24834)
-- Name: type_membre; Type: TABLE; Schema: public; Owner: padel_app
--

CREATE TABLE public.type_membre (
                                    delai_reservation_jours integer NOT NULL,
                                    id integer NOT NULL,
                                    code character varying(255) NOT NULL
);


ALTER TABLE public.type_membre OWNER TO padel_app;

--
-- TOC entry 237 (class 1259 OID 24833)
-- Name: type_membre_id_seq; Type: SEQUENCE; Schema: public; Owner: padel_app
--

ALTER TABLE public.type_membre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_membre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3322 (class 2604 OID 16453)
-- Name: jour_fermeture id; Type: DEFAULT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.jour_fermeture ALTER COLUMN id SET DEFAULT nextval('public.jour_fermeture_id_seq'::regclass);


--
-- TOC entry 3324 (class 2604 OID 16458)
-- Name: penalite id; Type: DEFAULT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.penalite ALTER COLUMN id SET DEFAULT nextval('public.penalite_id_seq'::regclass);


--
-- TOC entry 3524 (class 0 OID 24762)
-- Dependencies: 220
-- Data for Name: administrateur; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.administrateur
(id, matricule, site_id, type_admin, nom, prenom, email)
VALUES
    (1, 'AG01', NULL, 'GLOBAL', 'Admin', 'Global', 'admin.global@padel.be'),
    (2, 'AS02', 1, 'SITE', 'Admin', 'Bruxelles', 'admin.bruxelles@padel.be'),
    (3, 'AS03', 2, 'SITE', 'Admin', 'Liege', 'admin.liege@padel.be'),
    (4, 'AS04', 3, 'SITE', 'Admin', 'Arlon', 'admin.arlon@padel.be');


--
-- TOC entry 3526 (class 0 OID 24770)
-- Dependencies: 222
-- Data for Name: horaire_site; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.horaire_site VALUES (2026, 90, '08:00:00', '22:00:00', 1, 15, 1);
INSERT INTO public.horaire_site VALUES (2026, 90, '09:00:00', '21:00:00', 2, 15, 2);
INSERT INTO public.horaire_site VALUES (2026, 90, '08:30:00', '21:30:00', 3, 15, 3);


--
-- TOC entry 3519 (class 0 OID 16396)
-- Dependencies: 215
-- Data for Name: jour_fermeture; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.jour_fermeture VALUES (1, NULL, '2026-01-01', 'Nouvel an', true);
INSERT INTO public.jour_fermeture VALUES (2, NULL, '2026-12-25', 'Noël', true);
INSERT INTO public.jour_fermeture VALUES (3, 1, '2026-07-21', 'Fermeture exceptionnelle Bruxelles', false);
INSERT INTO public.jour_fermeture VALUES (4, 2, '2026-08-15', 'Fermeture exceptionnelle Liège', false);
INSERT INTO public.jour_fermeture VALUES (5, 3, '2026-11-11', 'Fermeture exceptionnelle Arlon', false);
INSERT INTO public.jour_fermeture VALUES (6, NULL, '2026-05-25', 'TEST', true);


--
-- TOC entry 3528 (class 0 OID 24776)
-- Dependencies: 224
-- Data for Name: match_padel; Type: TABLE DATA; Schema: public; Owner: padel_app
--


INSERT INTO public.match_padel VALUES ('2026-05-30', '12:30:00', '14:00:00', 6, 1, 60, 1, 10, NULL, 'COMPLET', 'PRIVE');
INSERT INTO public.match_padel VALUES ('2026-05-30', '15:00:00', '16:30:00', 7, 1, 60, 1, 11, '2026-05-24 17:05:50.553595', 'OUVERT', 'PUBLIC');
INSERT INTO public.match_padel VALUES ('2026-05-26', '14:00:00', '15:30:00', 8, 1, 60, 4, 12, '2026-05-24 17:41:39.839719', 'OUVERT', 'PUBLIC');

INSERT INTO public.match_padel VALUES ('2026-06-08', '11:00:00', '12:30:00', 41, 2, 60, 3, 45, '2026-05-25 10:56:53.598841', 'OUVERT', 'PUBLIC');
INSERT INTO public.match_padel VALUES ('2026-06-02', '12:30:00', '14:00:00', 42, 1, 60, 4, 46, '2026-05-25 11:11:21.567071', 'OUVERT', 'PUBLIC');
INSERT INTO public.match_padel VALUES ('2026-06-15', '10:00:00', '11:30:00', 43, 1, 60, 6, 47, '2026-05-25 11:22:37.190441', 'OUVERT', 'PUBLIC');

--
-- TOC entry 3530 (class 0 OID 24786)
-- Dependencies: 226
-- Data for Name: membre; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.membre VALUES (true, 1, NULL, 1, 'jean.dupont@mail.com', 'G0001', 'Dupont', 'Jean');
INSERT INTO public.membre VALUES (true, 2, NULL, 1, 'sophie.lambert@mail.com', 'G0002', 'Lambert', 'Sophie');
INSERT INTO public.membre VALUES (true, 3, 1, 2, 'claire.martin@mail.com', 'S0001', 'Martin', 'Claire');
INSERT INTO public.membre VALUES (true, 4, 1, 2, 'lucas.bernard@mail.com', 'S0002', 'Bernard', 'Lucas');
INSERT INTO public.membre VALUES (true, 5, 2, 2, 'emma.moreau@mail.com', 'S0003', 'Moreau', 'Emma');
INSERT INTO public.membre VALUES (true, 6, 3, 2, 'noah.lefevre@mail.com', 'S0004', 'Lefevre', 'Noah');
INSERT INTO public.membre VALUES (true, 7, NULL, 3, 'hugo.petit@mail.com', 'L0001', 'Petit', 'Hugo');
INSERT INTO public.membre VALUES (true, 8, NULL, 3, 'alice.durand@mail.com', 'L0002', 'Durand', 'Alice');
INSERT INTO public.membre VALUES (true, 9, NULL, 3, 'nathan.simon@mail.com', 'L0003', 'Simon', 'Nathan');
INSERT INTO public.membre VALUES (false, 10, NULL, 1, 'merlinestungroschnok@pigeon.voyageur', 'G0003', 'Pendragon', 'Arthur');


--
-- TOC entry 3532 (class 0 OID 24796)
-- Dependencies: 228
-- Data for Name: paiement; Type: TABLE DATA; Schema: public; Owner: padel_app
--



--
-- TOC entry 3534 (class 0 OID 24806)
-- Dependencies: 230
-- Data for Name: participation; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.participation VALUES (11, 6, 1, NULL, NULL);
INSERT INTO public.participation VALUES (12, 6, 8, NULL, NULL);
INSERT INTO public.participation VALUES (13, 6, 2, NULL, NULL);
INSERT INTO public.participation VALUES (14, 6, 7, NULL, NULL);
INSERT INTO public.participation VALUES (15, 7, 1, NULL, NULL);
INSERT INTO public.participation VALUES (16, 8, 1, NULL, '2026-05-24 17:41:39.843953');
INSERT INTO public.participation VALUES (49, 41, 2, NULL, '2026-05-25 10:56:53.60138');
INSERT INTO public.participation VALUES (50, 42, 1, NULL, '2026-05-25 11:11:21.568594');
INSERT INTO public.participation VALUES (51, 43, 1, NULL, '2026-05-25 11:22:37.192044');


--
-- TOC entry 3521 (class 0 OID 16426)
-- Dependencies: 217
-- Data for Name: penalite; Type: TABLE DATA; Schema: public; Owner: padel_app
--



--
-- TOC entry 3536 (class 0 OID 24814)
-- Dependencies: 232
-- Data for Name: reservation; Type: TABLE DATA; Schema: public; Owner: padel_app
--


INSERT INTO public.reservation VALUES (1, '2026-05-30', '14:00:00', 10, 1, '12:30:00');
INSERT INTO public.reservation VALUES (1, '2026-05-30', '16:30:00', 11, 1, '15:00:00');
INSERT INTO public.reservation VALUES (4, '2026-05-26', '15:30:00', 12, 1, '14:00:00');
INSERT INTO public.reservation VALUES (3, '2026-06-08', '12:30:00', 45, 2, '11:00:00');
INSERT INTO public.reservation VALUES (4, '2026-06-02', '14:00:00', 46, 1, '12:30:00');
INSERT INTO public.reservation VALUES (6, '2026-06-15', '11:30:00', 47, 1, '10:00:00');


--
-- TOC entry 3538 (class 0 OID 24820)
-- Dependencies: 234
-- Data for Name: site; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.site VALUES (true, 1, '-', '-', 'Situé au cœur de la capitale, ce centre propose des terrains indoor de dernière génération. Idéal pour une partie entre collègues ou un tournoi intensif.', 'images/bruxelles.jpg', 'THE ATOMIUM PADEL CLUB', 'BRUXELLES');
INSERT INTO public.site VALUES (true, 2, '-', '-', 'La "Cité Ardente" porte bien son nom ! Profitez de terrains spacieux et d''un club-house réputé pour sa convivialité et son ambiance unique.', 'images/liege.jpg', 'THE CARRÉ CLUB', 'LIÈGE');
INSERT INTO public.site VALUES (true, 3, '-', '-', 'À la frontière du Luxembourg, ce site offre un cadre verdoyant et apaisant. Des installations modernes parfaites pour s''évader du quotidien.', 'images/arlon.jpg', 'ARLON BLUE PADEL', 'ARLON');


--
-- TOC entry 3540 (class 0 OID 24828)
-- Dependencies: 236
-- Data for Name: terrain; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.terrain VALUES (true, true, 1, 1, 'B1');
INSERT INTO public.terrain VALUES (true, false, 2, 1, 'B2');
INSERT INTO public.terrain VALUES (true, true, 3, 2, 'L1');
INSERT INTO public.terrain VALUES (true, false, 4, 2, 'L2');
INSERT INTO public.terrain VALUES (true, true, 5, 3, 'A1');
INSERT INTO public.terrain VALUES (true, false, 6, 3, 'A2');


--
-- TOC entry 3542 (class 0 OID 24834)
-- Dependencies: 238
-- Data for Name: type_membre; Type: TABLE DATA; Schema: public; Owner: padel_app
--

INSERT INTO public.type_membre VALUES (21, 1, 'GLOBAL');
INSERT INTO public.type_membre VALUES (14, 2, 'SITE');
INSERT INTO public.type_membre VALUES (5, 3, 'LIBRE');

--
-- SEQUENCE SET
--

SELECT setval(
               pg_get_serial_sequence('public.administrateur', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.administrateur),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.horaire_site', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.horaire_site),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.jour_fermeture', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.jour_fermeture),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.match_padel', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.match_padel),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.membre', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.membre),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.paiement', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.paiement),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.participation', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.participation),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.penalite', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.penalite),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.reservation', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.reservation),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.site', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.site),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.terrain', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.terrain),
               true
       );

SELECT setval(
               pg_get_serial_sequence('public.type_membre', 'id'),
               (SELECT COALESCE(MAX(id), 1) FROM public.type_membre),
               true
       );
--
-- TOC entry 3335 (class 2606 OID 24768)
-- Name: administrateur administrateur_email_key; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.administrateur
    ADD CONSTRAINT administrateur_email_key UNIQUE (email);


--
-- TOC entry 3337 (class 2606 OID 24766)
-- Name: administrateur administrateur_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.administrateur
    ADD CONSTRAINT administrateur_pkey PRIMARY KEY (id);


--
-- TOC entry 3339 (class 2606 OID 24774)
-- Name: horaire_site horaire_site_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.horaire_site
    ADD CONSTRAINT horaire_site_pkey PRIMARY KEY (id);


--
-- TOC entry 3331 (class 2606 OID 16469)
-- Name: jour_fermeture jour_fermeture_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.jour_fermeture
    ADD CONSTRAINT jour_fermeture_pkey PRIMARY KEY (id);


--
-- TOC entry 3341 (class 2606 OID 24784)
-- Name: match_padel match_padel_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.match_padel
    ADD CONSTRAINT match_padel_pkey PRIMARY KEY (id);


--
-- TOC entry 3343 (class 2606 OID 24794)
-- Name: membre membre_matricule_key; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.membre
    ADD CONSTRAINT membre_matricule_key UNIQUE (matricule);


--
-- TOC entry 3345 (class 2606 OID 24792)
-- Name: membre membre_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.membre
    ADD CONSTRAINT membre_pkey PRIMARY KEY (id);


--
-- TOC entry 3347 (class 2606 OID 24804)
-- Name: paiement paiement_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.paiement
    ADD CONSTRAINT paiement_pkey PRIMARY KEY (id);


--
-- TOC entry 3349 (class 2606 OID 24812)
-- Name: participation participation_paiement_id_key; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.participation
    ADD CONSTRAINT participation_paiement_id_key UNIQUE (paiement_id);


--
-- TOC entry 3351 (class 2606 OID 24810)
-- Name: participation participation_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.participation
    ADD CONSTRAINT participation_pkey PRIMARY KEY (id);


--
-- TOC entry 3333 (class 2606 OID 16481)
-- Name: penalite penalite_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.penalite
    ADD CONSTRAINT penalite_pkey PRIMARY KEY (id);


--
-- TOC entry 3353 (class 2606 OID 24818)
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- TOC entry 3355 (class 2606 OID 24826)
-- Name: site site_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.site
    ADD CONSTRAINT site_pkey PRIMARY KEY (id);


--
-- TOC entry 3357 (class 2606 OID 24832)
-- Name: terrain terrain_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.terrain
    ADD CONSTRAINT terrain_pkey PRIMARY KEY (id);


--
-- TOC entry 3359 (class 2606 OID 24838)
-- Name: type_membre type_membre_pkey; Type: CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.type_membre
    ADD CONSTRAINT type_membre_pkey PRIMARY KEY (id);


--
-- TOC entry 3365 (class 2606 OID 24854)
-- Name: match_padel fk2d8dhmju12x9spk7irot9fqf6; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.match_padel
    ADD CONSTRAINT fk2d8dhmju12x9spk7irot9fqf6 FOREIGN KEY (terrain_id) REFERENCES public.terrain(id);


--
-- TOC entry 3373 (class 2606 OID 24894)
-- Name: reservation fk4vannohgd6e479gxbcwpvbniq; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk4vannohgd6e479gxbcwpvbniq FOREIGN KEY (membre_id) REFERENCES public.membre(id);


--
-- TOC entry 3367 (class 2606 OID 24859)
-- Name: membre fk4xouruxaxq2y3ytr4o9ne8f9d; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.membre
    ADD CONSTRAINT fk4xouruxaxq2y3ytr4o9ne8f9d FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- TOC entry 3369 (class 2606 OID 24869)
-- Name: paiement fk57valmvrpfcjhnemj2dmyf8fr; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.paiement
    ADD CONSTRAINT fk57valmvrpfcjhnemj2dmyf8fr FOREIGN KEY (participation_match_id) REFERENCES public.participation(id);


--
-- TOC entry 3370 (class 2606 OID 24884)
-- Name: participation fk6rqo0obcdcsv8f30ykmq2up0n; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.participation
    ADD CONSTRAINT fk6rqo0obcdcsv8f30ykmq2up0n FOREIGN KEY (paiement_id) REFERENCES public.paiement(id);


--
-- TOC entry 3375 (class 2606 OID 24899)
-- Name: terrain fk95rhv9d55dsl6gc4sabx4fimw; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.terrain
    ADD CONSTRAINT fk95rhv9d55dsl6gc4sabx4fimw FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- TOC entry 3360 (class 2606 OID 25046)
-- Name: jour_fermeture fk_jour_fermeture_site; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.jour_fermeture
    ADD CONSTRAINT fk_jour_fermeture_site FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- TOC entry 3361 (class 2606 OID 25056)
-- Name: penalite fk_penalite_match; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.penalite
    ADD CONSTRAINT fk_penalite_match FOREIGN KEY (match_id) REFERENCES public.match_padel(id);


--
-- TOC entry 3362 (class 2606 OID 25051)
-- Name: penalite fk_penalite_membre; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.penalite
    ADD CONSTRAINT fk_penalite_membre FOREIGN KEY (membre_id) REFERENCES public.membre(id);


--
-- TOC entry 3363 (class 2606 OID 24839)
-- Name: administrateur fkaekjbnyq3w62yg4bhs1pr8ksx; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.administrateur
    ADD CONSTRAINT fkaekjbnyq3w62yg4bhs1pr8ksx FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- TOC entry 3371 (class 2606 OID 24879)
-- Name: participation fkbsq6cwkl6w7p1l6l3l47t0pom; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.participation
    ADD CONSTRAINT fkbsq6cwkl6w7p1l6l3l47t0pom FOREIGN KEY (membre_id) REFERENCES public.membre(id);


--
-- TOC entry 3364 (class 2606 OID 24844)
-- Name: horaire_site fke21h843xmcbaimimomhv9ayxm; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.horaire_site
    ADD CONSTRAINT fke21h843xmcbaimimomhv9ayxm FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- TOC entry 3366 (class 2606 OID 24849)
-- Name: match_padel fki3x4l7ff1lyn8ia2glgysn3vw; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.match_padel
    ADD CONSTRAINT fki3x4l7ff1lyn8ia2glgysn3vw FOREIGN KEY (organisateur_id) REFERENCES public.membre(id);


--
-- TOC entry 3368 (class 2606 OID 24864)
-- Name: membre fki5vl2230wjuomqyfinn7lr9dk; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.membre
    ADD CONSTRAINT fki5vl2230wjuomqyfinn7lr9dk FOREIGN KEY (type_membre_id) REFERENCES public.type_membre(id);


--
-- TOC entry 3372 (class 2606 OID 24874)
-- Name: participation fkl3vc9gq7x2gapqn3e11i4of6g; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.participation
    ADD CONSTRAINT fkl3vc9gq7x2gapqn3e11i4of6g FOREIGN KEY (match_id) REFERENCES public.match_padel(id);


--
-- TOC entry 3374 (class 2606 OID 24889)
-- Name: reservation fkmi7rw0to79afldrhpopfgvn0o; Type: FK CONSTRAINT; Schema: public; Owner: padel_app
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkmi7rw0to79afldrhpopfgvn0o FOREIGN KEY (court_id) REFERENCES public.terrain(id);


--
-- TOC entry 3549 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: padel_app
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2026-05-25 11:30:56

--
-- PostgreSQL database dump complete
--

