BEGIN;

ALTER TABLE public.participation
    ADD COLUMN IF NOT EXISTS statut character varying(50) DEFAULT 'EN_ATTENTE_PAIEMENT' NOT NULL,
    ADD COLUMN IF NOT EXISTS montant_du_centimes integer DEFAULT 1500 NOT NULL,
    ADD COLUMN IF NOT EXISTS date_limite_paiement timestamp(6) without time zone;

UPDATE public.participation p
SET date_limite_paiement = (mp.date_match - INTERVAL '1 day') + mp.heure_debut
FROM public.match_padel mp
WHERE p.match_id = mp.id
  AND p.date_limite_paiement IS NULL;

ALTER TABLE public.participation
    DROP CONSTRAINT IF EXISTS participation_montant_du_centimes_check,
    DROP CONSTRAINT IF EXISTS participation_statut_check,
    ADD CONSTRAINT participation_montant_du_centimes_check CHECK (montant_du_centimes >= 0),
    ADD CONSTRAINT participation_statut_check CHECK (statut IN ('EN_ATTENTE_PAIEMENT', 'PAYEE', 'LIBEREE', 'ANNULEE'));

ALTER TABLE public.paiement
    ADD COLUMN IF NOT EXISTS membre_id integer;

UPDATE public.paiement p
SET membre_id = part.membre_id
FROM public.participation part
WHERE p.participation_match_id = part.id
  AND p.membre_id IS NULL;

UPDATE public.paiement p
SET membre_id = r.membre_id
FROM public.reservation r
WHERE p.reservation_id = r.id
  AND p.membre_id IS NULL;

ALTER TABLE public.paiement
    ALTER COLUMN membre_id SET NOT NULL,
    DROP CONSTRAINT IF EXISTS fk_paiement_membre,
    ADD CONSTRAINT fk_paiement_membre FOREIGN KEY (membre_id) REFERENCES public.membre(id);

CREATE TABLE IF NOT EXISTS public.dette_membre (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membre_id integer NOT NULL REFERENCES public.membre(id),
    participation_id integer REFERENCES public.participation(id),
    reservation_id integer REFERENCES public.reservation(id),
    montant_centimes integer NOT NULL,
    statut character varying(50) DEFAULT 'OUVERTE' NOT NULL,
    raison character varying(50) DEFAULT 'PARTICIPATION_IMPAYEE' NOT NULL,
    date_creation timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_resolution timestamp(6) without time zone,

    CONSTRAINT dette_membre_montant_centimes_check CHECK (montant_centimes > 0),
    CONSTRAINT dette_membre_statut_check CHECK (statut IN ('OUVERTE', 'PAYEE', 'ANNULEE')),
    CONSTRAINT dette_membre_raison_check CHECK (raison IN ('PARTICIPATION_IMPAYEE', 'SOLDE_ORGANISATEUR', 'AJUSTEMENT'))
);

UPDATE public.participation p
SET statut = 'PAYEE'
WHERE EXISTS (
    SELECT 1
    FROM public.paiement pa
    WHERE pa.participation_match_id = p.id
      AND pa.statut = 'VALIDE'
);

COMMIT;
