spring.application.name=PadelBack

spring.datasource.url=jdbc:postgresql://localhost:5432/padel
spring.datasource.username=padel_app
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect